### ISSUE TITLE
Hope add tree component.

### ISSUE THREAD

**Issue by keyiis** [valor-software/ng2-plans#7]
Like jstree,support drag&drop edit sort ......

**Comment by valorkin** [comment]
@keyiis https://github.com/valor-software/ng2-tree
like this one? :)
@rychkog already working on it

**Comment by keyiis** [comment]
@valorkin First of thank you for this job! i already try ng2-tree,before post this request.but has some probleme, ex:
if i select some text in page before dragging node,the text will move follow the dragging node
![1](https://cloud.githubusercontent.com/assets/7766085/17353526/0a245f90-5973-11e6-8dd8-fa82e1cdc9ab.JPG)

**Comment by valorkin** [comment]
added to modules list

**Comment by keyiis** [comment]
@valorkin there a new issues,
when droped a tree node,will tigger the sbling node hover style,hut the style hold until hover the node again.
